// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: command.proto

#include "command.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace command {
namespace msg {
        template <typename>
PROTOBUF_CONSTEXPR CommandMessage::CommandMessage(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_.command_)*/ 0,
      /*decltype(_impl_._cached_size_)*/ {},
    } {}
struct CommandMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CommandMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CommandMessageDefaultTypeInternal() {}
  union {
    CommandMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CommandMessageDefaultTypeInternal _CommandMessage_default_instance_;
}  // namespace msg
}  // namespace command
static ::_pb::Metadata file_level_metadata_command_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_command_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_command_2eproto = nullptr;
const ::uint32_t TableStruct_command_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::command::msg::CommandMessage, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::command::msg::CommandMessage, _impl_.command_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::command::msg::CommandMessage)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::command::msg::_CommandMessage_default_instance_._instance,
};
const char descriptor_table_protodef_command_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\rcommand.proto\022\013command.msg\"7\n\016CommandM"
    "essage\022%\n\007command\030\001 \001(\0162\024.command.msg.Co"
    "mmand*V\n\007Command\022\020\n\014COMMAND_INFO\020\000\022\022\n\016CO"
    "MMAND_LED_ON\020\001\022\023\n\017COMMAND_LED_OFF\020\002\022\020\n\014C"
    "OMMAND_EXIT\020\003b\006proto3"
};
static ::absl::once_flag descriptor_table_command_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_command_2eproto = {
    false,
    false,
    181,
    descriptor_table_protodef_command_2eproto,
    "command.proto",
    &descriptor_table_command_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_command_2eproto::offsets,
    file_level_metadata_command_2eproto,
    file_level_enum_descriptors_command_2eproto,
    file_level_service_descriptors_command_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_command_2eproto_getter() {
  return &descriptor_table_command_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_command_2eproto(&descriptor_table_command_2eproto);
namespace command {
namespace msg {
const ::google::protobuf::EnumDescriptor* Command_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_command_2eproto);
  return file_level_enum_descriptors_command_2eproto[0];
}
bool Command_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}
// ===================================================================

class CommandMessage::_Internal {
 public:
};

CommandMessage::CommandMessage(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:command.msg.CommandMessage)
}
CommandMessage::CommandMessage(const CommandMessage& from)
    : ::google::protobuf::Message(), _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:command.msg.CommandMessage)
}
inline void CommandMessage::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.command_){0},
      /*decltype(_impl_._cached_size_)*/ {},
  };
}
CommandMessage::~CommandMessage() {
  // @@protoc_insertion_point(destructor:command.msg.CommandMessage)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CommandMessage::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
}
void CommandMessage::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void CommandMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:command.msg.CommandMessage)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.command_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CommandMessage::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> CommandMessage::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CommandMessage_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // .command.msg.Command command = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CommandMessage, _impl_.command_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(CommandMessage, _impl_.command_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .command.msg.Command command = 1;
    {PROTOBUF_FIELD_OFFSET(CommandMessage, _impl_.command_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* CommandMessage::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:command.msg.CommandMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .command.msg.Command command = 1;
  if (this->_internal_command() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_command(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:command.msg.CommandMessage)
  return target;
}

::size_t CommandMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:command.msg.CommandMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .command.msg.Command command = 1;
  if (this->_internal_command() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_command());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData CommandMessage::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    CommandMessage::MergeImpl
};
const ::google::protobuf::Message::ClassData*CommandMessage::GetClassData() const { return &_class_data_; }


void CommandMessage::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CommandMessage*>(&to_msg);
  auto& from = static_cast<const CommandMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:command.msg.CommandMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_command() != 0) {
    _this->_internal_set_command(from._internal_command());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CommandMessage::CopyFrom(const CommandMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:command.msg.CommandMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CommandMessage::IsInitialized() const {
  return true;
}

void CommandMessage::InternalSwap(CommandMessage* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.command_, other->_impl_.command_);
}

::google::protobuf::Metadata CommandMessage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_command_2eproto_getter, &descriptor_table_command_2eproto_once,
      file_level_metadata_command_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace msg
}  // namespace command
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
