[package]
name = "tcp_app"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.4.0"
prost = "0.11.9"

[build-dependencies]
prost-build = "0.11.9"